# Generated by Django 5.0.4 on 2024-04-10 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_setup', '0003_blogsetup_delete_menulinkadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='menulink',
            name='blog_setup',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_setup.blogsetup'),
        ),
    ]
