# Generated by Django 5.0.4 on 2024-04-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_setup', '0004_menulink_blog_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsetup',
            name='favicon',
            field=models.ImageField(blank=True, default='', upload_to='assets/favicon/%Y/%m'),
        ),
    ]
